financial algorithm post
FiQCI/fiqci.github.io pull request #38
Opened 2024-04-09 11:23 UTC by TheKharleeci

Changes:

- Add Olli's Financial algorithms blog post
- Add new Images ( This will still be used on the home page)
- Edit FiQCI bio- It basically said "We build FiQCI" before
- Remove "Move to top" sign ( Looking for an alternative or to make it cleaner)

2024-04-09 11:30 UTC, JMuff22 commented on _posts/2024-04-09-Financial-Algorithms.md
> +    <em>Figure 5: CSC had a team mentoring at Hanken Quantum Hackathon. Pictured at the bottom left: Nikolas, Olli, Modupe and Jake.</em>
I would suggest full names

2024-04-09 11:32 UTC, JMuff22 commented
I would prefer to add images along with home page changes in a separate pull request.

2024-04-09 11:33 UTC, JLenssen commented
- The blog post titles are currently underlined in `/publications` can we remove the lines?
- Pictures in blog post overview page are quite small. Can we make them slightly larger?
- `Watch this space for the latest news and posts of interest!` <= imo not needed. It's clear what this page is about.

2024-04-09 11:36 UTC, JLenssen commented on _posts/2024-04-09-Financial-Algorithms.md
> +Now is the time to identify algorithms with future potential. Many applications have already been singled out: cryptography, simulations, search algorithms, and optimization problems. In finance, the
Any chance we can make the links clickable?

2024-04-09 11:38 UTC, JLenssen commented on _posts/2024-04-09-Financial-Algorithms.md
> +The impatient Reader, who just wants to know how all of this works in practice, can skip to the next section. The technically inclined should read on.
Reader -> reader

2024-04-09 11:41 UTC, JLenssen commented on _posts/2024-04-09-Financial-Algorithms.md
> +5.	[Improved maximum-likelihood quantum amplitude estimation, A. Callison, D. Browne, 2023](https://arxiv.org/abs/2209.03321)
A. Callison _and_ D. Browne

2024-04-09 12:18 UTC, olmuk commented
> 



> * The blog post titles are currently underlined in `/publications` can we remove the lines?
> * Pictures in blog post overview page are quite small. Can we make them slightly larger?
> * `Watch this space for the latest news and posts of interest!` <= imo not needed. It's clear what this page is about.

@JLenssen Do you mean all of the pictures? We can make them larger

2024-04-09 12:48 UTC, JLenssen approved these changes

2024-04-09 13:12 UTC, olmuk commented on _posts/2024-04-09-Financial-Algorithms.md
> +Last November, the Hanken School of Economics in Finland and Ultrahack organized a quantum hackathon for finance-oriented minds with the theme of sustainable finance in the quantum era. The competiti
"Taking part in supporting the event, CSC with colleagues from VTT and IQM " -> "Taking part in supporting the event, CSC and VTT with colleagues from IQM "

2024-04-09 13:16 UTC, olmuk commented
Let's add the name of the author. Also, let's see if we can add a picture of the author

2024-04-10 07:05 UTC, JMuff22 requested changes

2024-04-10 07:05 UTC, JMuff22 commented on _layouts/posts.html
> +    <!-- <a href="#page-title" class="back-to-top">{{ site.data.ui-text[site.locale].back_to_top | default: 'Back to Top' }} &uarr;</a> -->
Lets remove this instead of commenting it out

2024-04-10 07:05 UTC, JMuff22 commented on _pages/publications.md
> +<!-- Watch this space for the latest news and posts of interest! -->
Lets remove this instead of commenting it out

2024-04-10 10:13 UTC, olmuk approved these changes

2024-04-10 10:26 UTC, merged